import DashboardLayout from "@/components/DashboardLayout";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Eye, EyeOff, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

export default function CatalogAdmin() {
  const { user } = useAuth();
  const catalog = trpc.catalog.list.useQuery();
  const updateAvailability = trpc.adminCatalog.setAvailability.useMutation({ onSuccess: () => catalog.refetch() });
  return <DashboardLayout><section className="min-h-screen -m-4 bg-[#080a08] p-5 text-[#f3f0e6] md:p-9"><div className="mx-auto max-w-6xl"><Link href="/admin/payments" className="mb-6 inline-flex items-center gap-2 text-xs text-[#c7f34a]"><ArrowLeft size={14} /> Payment review</Link><div className="mb-9 border-b border-white/10 pb-7"><div className="mb-3 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.18em] text-[#c7f34a]"><ShieldCheck size={14} /> Roth / source catalog controls</div><h1 className="font-['Space_Grotesk'] text-4xl font-medium tracking-[-.07em] md:text-6xl">Availability,<br /><span className="text-[#c7f34a]">not invention.</span></h1><p className="mt-4 max-w-2xl text-sm leading-6 text-[#96a091]">The repository remains the source of truth for products, variants, and listed prices. This desk only controls whether an imported route is visible and purchasable; it does not create fake products or overwrite source prices.</p></div>{!user ? <div className="border border-white/15 p-5 text-sm text-[#a8b1a4]">Sign in with the owner account to open catalog controls.</div> : user.role !== "admin" ? <div className="border border-[#ffb4a7]/30 bg-[#702014]/20 p-5 text-sm text-[#ffb4a7]">This account does not have admin access.</div> : catalog.isLoading ? <div className="border border-white/10 p-12 text-center text-sm uppercase tracking-[.16em] text-[#8f9a8d]">Opening catalog controls…</div> : <div className="overflow-hidden border border-white/10 bg-[#0d110d]"><div className="hidden grid-cols-[1.5fr_.8fr_.7fr_.6fr] gap-4 border-b border-white/10 bg-white/[.025] px-5 py-3 text-[9px] font-semibold uppercase tracking-[.15em] text-[#7f8a7c] md:grid"><span>Repository product</span><span>Category</span><span>Displayed price</span><span>Visibility</span></div>{catalog.data?.products.map((product) => { const productId = `${product.group} — ${product.label}`; const unavailable = Boolean(catalog.data.availability?.[productId]); return <div className="grid gap-4 border-b border-white/10 px-5 py-5 last:border-b-0 md:grid-cols-[1.5fr_.8fr_.7fr_.6fr] md:items-center" key={productId}><div><p className="font-['Space_Grotesk'] text-base tracking-[-.035em] text-[#f0f3ea]">{product.group}</p><p className="mt-1 text-xs text-[#899487]">{product.label}</p></div><span className="text-xs text-[#a6b0a1]">{catalog.data.categories[product.category]}</span><span className="font-['Space_Grotesk'] text-lg text-[#c7f34a]">{product.pay}</span><button onClick={() => updateAvailability.mutate({ productId, unavailable: !unavailable })} disabled={updateAvailability.isPending} className={`inline-flex w-fit items-center gap-2 border px-3 py-2 text-[10px] font-semibold uppercase tracking-[.12em] ${unavailable ? "border-[#ffcc92]/40 text-[#ffcc92]" : "border-[#c7f34a]/40 text-[#c7f34a]"}`}>{unavailable ? <><EyeOff size={13} /> Hidden</> : <><Eye size={13} /> Visible</>}</button></div>; })}</div>}</div></section></DashboardLayout>;
}
