import StoreShell from "@/components/StoreShell";
import { useLocation } from "wouter";

const policyContent = {
  about: { kicker: "ABOUT / ROTH DIGITAL", title: ["Private access.", "Clear handoffs."], intro: "ROTH DIGITAL is a wallet-first storefront for the repository-backed digital-access catalog shown on this site.", sections: [["What the desk does", "The storefront presents catalog routes, shows the selected payment amount and public receiving address, records visible chain status, and routes confirmed payments into administrator review."], ["What the desk does not promise", "Product availability, regional eligibility, and fulfillment timing can depend on the selected item and approval state. The site does not publish invented claims, ratings, or delivery guarantees."], ["How orders move", "A customer selects a catalog item, creates a specific crypto payment order, sends the exact amount on the chosen network, and checks confirmation state. Confirmed orders require manual administrator approval before fulfillment."]] },
  refunds: { kicker: "REFUND & CANCELLATION POLICY", title: ["Simple rules.", "Clear outcomes."], intro: "This policy explains the current refund and cancellation process for digital-access orders. Please have the final version reviewed for your applicable jurisdiction before publishing.", sections: [["Cancel before payment", "You can leave checkout any time before sending payment. Unpaid payment orders expire automatically after the displayed checkout window."], ["Request a cancellation", "If you have already sent payment, contact support as soon as possible with your order ID. We will review whether the payment is confirmed, whether the order has been approved, and whether delivery has started."], ["Digital products", "Digital products, codes, subscriptions, and top-ups are generally not refundable once they have been delivered, revealed, redeemed, or activated. If an item has not been delivered because of a verified issue, contact support so the order can be reviewed."], ["Wrong network or amount", "Send only the exact amount on the selected network. Payments sent on the wrong network or in an incorrect amount may not be matched automatically and can require manual review. Blockchain transfers cannot normally be reversed after confirmation."], ["How refunds are handled", "Where a refund is approved, we will confirm the process and relevant details through support. Approval is assessed case by case and does not affect your rights under applicable consumer law."]] },
  terms: { kicker: "TERMS & CONDITIONS", title: ["Use the desk.", "Respect the flow."], intro: "These terms explain the current catalog, payment, and review flow in plain language. They should receive a jurisdiction-appropriate legal review before a final business launch.", sections: [["Catalog information", "Catalog product labels, displayed prices, original prices, variants, and categories are sourced from the connected repository. A displayed item may be subject to regional, stock, or provider limitations."], ["Crypto payments", "A checkout order identifies a selected network, public receiving address, exact payment amount, and expiry. Sending funds on a wrong network, in an incorrect amount, or after expiry can delay or prevent matching."], ["Manual fulfillment", "Blockchain confirmation does not equal automatic delivery. A confirmed payment moves to manual review, where the administrator can approve or reject it according to the applicable order state."], ["Customer responsibilities", "Customers must supply accurate order information, safeguard their own wallet credentials, and never send private keys or recovery phrases through the site or support channel."]] },
  privacy: { kicker: "PRIVACY", title: ["Less collection.", "Clear purpose."], intro: "This notice explains the current information-handling practices for the storefront. It should receive a jurisdiction-appropriate legal review before a final business launch.", sections: [["Information handled", "The service can process account identifiers supplied through sign-in, cart selections stored locally in the browser, payment order metadata, blockchain transaction identifiers, and support messages submitted through a configured channel."], ["Why information is used", "Order data is used to create payment orders, display payment status, support administrator review, provide customer order history for signed-in customers, and investigate support requests."], ["What is not requested", "Checkout does not request wallet private keys, seed phrases, or exchange passwords. Do not send them to support."], ["Retention and sharing", "Retention periods, legal bases, and provider-specific sharing practices must be finalised once the business operator, support provider, email provider, and jurisdiction are confirmed."]] },
} as const;

export default function PolicyPage() {
  const [location] = useLocation();
  const key = (location.split("/")[1] || "about") as keyof typeof policyContent;
  const content = policyContent[key] ?? policyContent.about;
  return <StoreShell><section className="policy-page"><span className="catalog-kicker">{content.kicker}</span><h1>{content.title[0]}<br /><em>{content.title[1]}</em></h1><p className="policy-intro">{content.intro}</p><div className="policy-sections">{content.sections.map(([title, body], index) => <article key={title}><span>0{index + 1}</span><div><h2>{title}</h2><p>{body}</p></div></article>)}</div></section></StoreShell>;
}
