import StoreShell from "@/components/StoreShell";
import { imageForProduct } from "@/components/RealCatalog";
import { useCart } from "@/contexts/CartContext";
import { brandAlt, cleanBrand } from "@/lib/sanitize";
import { trpc } from "@/lib/trpc";
import { useStorePreferences } from "@/contexts/StorePreferencesContext";
import { ArrowLeft, ArrowUpRight, Check, ShoppingBag } from "lucide-react";
import { Link, useRoute } from "wouter";

const clean = (value: string) => cleanBrand(value).replace(/^[^A-Za-z0-9]+/, "");

export default function ProductPage() {
  const [, params] = useRoute("/product/:id"); const itemId = params?.id ? decodeURIComponent(params.id) : ""; const { addItem } = useCart(); const { formatPrice } = useStorePreferences(); const { data, isLoading } = trpc.catalog.list.useQuery(); const product = (data?.products ?? []).find((item) => `${item.group} — ${item.label}` === itemId);
  if (isLoading) return <StoreShell><div className="commerce-empty">Opening product route…</div></StoreShell>; if (!product) return <StoreShell><div className="commerce-empty"><p>That product route is unavailable.</p><Link href="/">Return to the catalog</Link></div></StoreShell>;
  const category = clean(data?.categories[product.category] ?? product.category); const isVcc = product.category === "vcc"; const unavailable = Boolean(data?.availability[itemId]); const quoteOnly = Boolean(product.quoteOnly); const image = imageForProduct(product.group, product.category, product.label);
  return <StoreShell><section className="product-detail"><Link href={isVcc ? "/vcc" : `/category/${product.category}`} className="back-link"><ArrowLeft size={15} /> Back to {isVcc ? "VCC desk" : category}</Link><div className="product-detail-layout"><div className={`product-detail-plate ${isVcc ? "vcc-detail-plate" : ""}`}><span>{isVcc ? "ROTH / VCC ROUTE" : "ROTH / PRODUCT DETAIL"}</span><strong>{cleanBrand(product.group)}</strong>{!isVcc && image ? <img src={image} alt={brandAlt(product.group)} style={{ width: "min(100%, 360px)", height: "240px", margin: "18px auto 0", objectFit: "contain", border: "1px solid rgba(199,243,74,.28)", background: "rgba(8,10,8,.36)" }} /> : <div className="detail-mark">{isVcc ? "••••" : "R"}</div>}{isVcc && <small>{unavailable ? "ROUTE UNAVAILABLE" : "MANUAL HANDOFF"}</small>}</div><div className="product-detail-copy"><span className="catalog-kicker">{category} / VERIFIED LISTING</span><h1>{product.label}</h1>{product.get && <p className="detail-package">{product.get}</p>}<div className="detail-price"><strong>{formatPrice(product.pay)}</strong>{product.origPay && <s>{formatPrice(product.origPay)}</s>}</div><div className="detail-facts"><div><Check size={15} /><span><b>Price shown</b>{quoteOnly ? "Custom quote required before any checkout" : "Repository-backed price at checkout"}</span></div><div><Check size={15} /><span><b>Funding status</b>Wallet funding confirmation before admin review</span></div><div><Check size={15} /><span><b>{isVcc ? "Credential boundary" : "Delivery state"}</b>{isVcc ? "Issued credentials require approved secure handoff" : "Manual approval required before fulfillment"}</span></div></div>{quoteOnly ? <div className="detail-variants"><span>MANUAL QUOTE</span><p>This service requires a custom review before a quote can be issued. It cannot be added to cart.</p></div> : unavailable ? <div className="detail-variants"><span>AVAILABILITY</span><p>This route is currently unavailable and cannot be ordered.</p></div> : product.colors?.length ? <div className="detail-variants"><span>AVAILABLE VARIANTS</span><p>{product.colors.join(" · ")}</p></div> : null}<div className="detail-actions">{quoteOnly ? <Link href="/support" className="button-primary">Request manual quote <ArrowUpRight size={16} /></Link> : <><button className="button-outline" disabled={unavailable} onClick={() => addItem({ itemId, group: cleanBrand(product.group), label: product.label, category, price: product.pay })}><ShoppingBag size={16} /> {unavailable ? "Unavailable" : "Add to cart"}</button>{unavailable ? <span className="button-outline">Checkout paused</span> : <Link href={`/checkout?item=${encodeURIComponent(itemId)}`} className="button-primary">Wallet checkout <ArrowUpRight size={16} /></Link>}</>}</div></div></div></section></StoreShell>;
}
